"""add provider accounts and leases

Revision ID: 134e65479fc3
Revises: 
Create Date: 2026-09-17 12:58:40.299429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134e65479fc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('external_identity', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('profile_key', sa.String(length=255), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_key')
    )
    op.create_index('ix_provider_accounts_cooldown_until', 'provider_accounts', ['cooldown_until'], unique=False)
    op.create_index('ix_provider_accounts_last_used_at', 'provider_accounts', ['last_used_at'], unique=False)
    op.create_index('ix_provider_accounts_provider_status', 'provider_accounts', ['provider_key', 'status'], unique=False)
    op.create_table('account_leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['provider_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index('ix_account_leases_expires_at', 'account_leases', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_leases_expires_at', table_name='account_leases')
    op.drop_table('account_leases')
    op.drop_index('ix_provider_accounts_provider_status', table_name='provider_accounts')
    op.drop_index('ix_provider_accounts_last_used_at', table_name='provider_accounts')
    op.drop_index('ix_provider_accounts_cooldown_until', table_name='provider_accounts')
    op.drop_table('provider_accounts')
    # ### end Alembic commands ###
