import type {
  Chapter,
  AnalyzedScene,
  VisualBeat,
  AnalysisSettings,
  AnalysisResult,
  AnalysisProgressStep,
} from "../model/types"
import { demoProjects, demoAvatars } from "@/shared/demo"

export const INITIAL_CHAPTERS: Chapter[] = [
  {
    id: "chap-01",
    projectId: "proj-default",
    order: 1,
    title: "Khởi đầu hành trình",
    summary: "Gặp gỡ sư phụ và nhận kiếm cổ tại chân núi...",
    sourceText: "Tiêu Viêm rời khỏi gia tộc, bắt đầu bước chân vào hành trình tu luyện đầy gian nan...",
    status: "analyzed",
    stats: {
      wordCount: 850,
      sceneCount: 3,
      visualBeatCount: 8,
    },
    updatedAt: "2 giờ trước",
  },
  {
    id: "chap-02",
    projectId: "proj-default",
    order: 2,
    title: "Rừng sương mù",
    summary: "Vượt qua cạm bẫy và chạm trán bầy quái...",
    sourceText: "Sương mù dày đặc bao phủ toàn bộ khu rừng bí ẩn, mỗi bước chân đều ẩn chứa nguy hiểm khôn lường...",
    status: "analyzed",
    stats: {
      wordCount: 1620,
      sceneCount: 5,
      visualBeatCount: 15,
    },
    updatedAt: "Hôm qua",
  },
  {
    id: "chap-03",
    projectId: "proj-default",
    order: 3,
    title: "Bí mật cổ mộ",
    summary: "Khám phá lăng mộ ngàn năm và tìm thấy bí kíp thất truyền. Cả nhóm đối mặt với bẫy cơ quan cổ đại.",
    sourceText: `Lối vào cổ mộ bị che phủ bởi lớp rêu phong dày đặc hàng trăm năm. Tiêu Viêm đưa tay phủi nhẹ lớp bụi trên phiến đá, để lộ ra những ký tự cổ đại phát ra ánh sáng lam nhạt.

"Đây chính là nơi phong ấn Hồn Cốt Quyết," Tiêu Viêm thì thầm, ánh mắt sáng lên tia hy vọng. Bên cạnh, Dược Lão vuốt râu trầm ngâm, thần sắc có phần ngưng trọng hơn thường lệ.

Đột nhiên, mặt đất rung chuyển dữ dội. Những cột đá xung quanh bắt đầu sụp đổ. Một bóng đen khổng lồ từ từ trồi lên từ vực sâu phía sau điện thờ. Đôi mắt đỏ rực như hai hòn than cháy nhìn chằm chằm vào những kẻ xâm nhập bất hợp pháp.

"Cẩn thận! Hộ mộ thú đã thức tỉnh!" Dược Lão hét lớn, đồng thời vung tay tạo ra một màn chắn năng lượng màu xanh ngọc bích bao bọc lấy cả hai.`,
    status: "draft",
    stats: {
      wordCount: 1240,
      sceneCount: 4,
      visualBeatCount: 12,
    },
    updatedAt: "Vừa xong",
  },
  {
    id: "chap-04",
    projectId: "proj-default",
    order: 4,
    title: "Trận chiến đỉnh núi",
    summary: "Quyết đấu với Ma Vương bảo vệ phong ấn...",
    sourceText: "Gió rít gào trên đỉnh núi tuyết phủ. Trận chiến quyết định vận mệnh toàn đại lục bắt đầu nổ ra...",
    status: "draft",
    stats: {
      wordCount: 2100,
      sceneCount: 0,
      visualBeatCount: 0,
    },
    updatedAt: "3 ngày trước",
  },
]

export const DEMO_ANALYZED_SCENES: Record<string, AnalyzedScene[]> = {
  "chap-01": [
    {
      id: "scene-1-1",
      chapterId: "chap-01",
      sceneNumber: 1,
      title: "Rời khỏi gia tộc",
      estimatedDuration: "0:50",
      sceneType: "Ngoại cảnh",
      location: "Cổng thành Tiêu Gia",
      promptPreview: "Thiếu niên Tiêu Viêm ngoảnh đầu nhìn lại cổng thành gia tộc lần cuối dưới ánh hoàng hôn...",
      visualBeatCount: 3,
    },
    {
      id: "scene-1-2",
      chapterId: "chap-01",
      sceneNumber: 2,
      title: "Chân núi Ma Thú",
      estimatedDuration: "1:10",
      sceneType: "Ngoại cảnh",
      location: "Chân dãy núi Ma Thú",
      promptPreview: "Bóng lưng cô độc bước đi trên con đường mòn phủ đầy lá khô, rừng cây rậm rạp ngút ngàn...",
      visualBeatCount: 3,
    },
    {
      id: "scene-1-3",
      chapterId: "chap-01",
      sceneNumber: 3,
      title: "Chiếc nhẫn đen thức tỉnh",
      estimatedDuration: "1:00",
      sceneType: "Nội cảnh",
      location: "Hang đá tạm trú",
      promptPreview: "Ánh sáng bạc le lói từ chiếc nhẫn cổ trên ngón tay, làn sương trắng từ từ ngưng tụ thành hình bóng Dược Lão...",
      visualBeatCount: 2,
    },
  ],
  "chap-02": [
    {
      id: "scene-2-1",
      chapterId: "chap-02",
      sceneNumber: 1,
      title: "Rừng sương mù dày đặc",
      estimatedDuration: "0:40",
      sceneType: "Ngoại cảnh",
      location: "Bìa rừng sương mù",
      promptPreview: "Sương mù trắng xoá che khuất tầm nhìn, tiếng gió rít qua kẽ lá như tiếng thú gầm gừ...",
      visualBeatCount: 3,
    },
    {
      id: "scene-2-2",
      chapterId: "chap-02",
      sceneNumber: 2,
      title: "Chạm trán Độc Giác Lang",
      estimatedDuration: "1:15",
      sceneType: "Ngoại cảnh",
      location: "Khe suối cạn",
      promptPreview: "Bầy sói một sừng với đôi mắt xanh le lói bao vây, Tiêu Viêm nắm chặt chuôi Huyền Trọng Cước...",
      visualBeatCount: 3,
    },
    {
      id: "scene-2-3",
      chapterId: "chap-02",
      sceneNumber: 3,
      title: "Bát Cực Băng xuất kích",
      estimatedDuration: "1:20",
      sceneType: "Ngoại cảnh",
      location: "Bãi đá ngầm",
      promptPreview: "Đấu khí bùng nổ, nắm đấm mang kình lực暗 kình phát ra tiếng nổ giòn giã đẩy lùi đầu đàn...",
      visualBeatCount: 3,
    },
    {
      id: "scene-2-4",
      chapterId: "chap-02",
      sceneNumber: 4,
      title: "Dược thảo quý hiếm",
      estimatedDuration: "0:45",
      sceneType: "Nội cảnh",
      location: "Vách đá rêu phong",
      promptPreview: "Bông Hồi Khí Thảo nở rộ giữa kẽ đá tỏa hương thơm dịu nhẹ trong ánh nắng ban mai...",
      visualBeatCount: 3,
    },
    {
      id: "scene-2-5",
      chapterId: "chap-02",
      sceneNumber: 5,
      title: "Dược Lão chỉ điểm luyện đan",
      estimatedDuration: "1:00",
      sceneType: "Nội cảnh",
      location: "Sơn động bí mật",
      promptPreview: "Ngọn lửa tím xanh bùng cháy trong đỉnh đồng nhỏ, Dược Lão chỉ dẫn cách khống chế hỏa hầu...",
      visualBeatCount: 3,
    },
  ],
  "chap-03": [
    {
      id: "scene-3-1",
      chapterId: "chap-03",
      sceneNumber: 1,
      title: "Lối vào cổ mộ",
      estimatedDuration: "0:45",
      sceneType: "Ngoại cảnh",
      location: "Cửa cổ mộ",
      promptPreview: "Tiêu Viêm phủi bụi trên phiến đá cổ, ký tự phát sáng lam nhạt giữa rừng sương mù u tịch...",
      visualBeatCount: 3,
    },
    {
      id: "scene-3-2",
      chapterId: "chap-03",
      sceneNumber: 2,
      title: "Khám phá điện thờ",
      estimatedDuration: "1:15",
      sceneType: "Nội cảnh",
      location: "Điện thờ chính",
      promptPreview: "Bên trong lăng mộ u ám, Tiêu Viêm và Dược Lão tìm kiếm Hồn Cốt Quyết bên bàn thờ đá cổ kính...",
      visualBeatCount: 4,
    },
    {
      id: "scene-3-3",
      chapterId: "chap-03",
      sceneNumber: 3,
      title: "Hộ mộ thú thức tỉnh",
      estimatedDuration: "1:30",
      sceneType: "Nội cảnh",
      location: "Vực sâu điện thờ",
      promptPreview: "Mặt đất rung chuyển dữ dội, bóng đen khổng lồ với đôi mắt đỏ rực trồi lên từ vực sâu...",
      visualBeatCount: 3,
    },
    {
      id: "scene-3-4",
      chapterId: "chap-03",
      sceneNumber: 4,
      title: "Màn chắn ngọc bích",
      estimatedDuration: "1:00",
      sceneType: "Nội cảnh",
      location: "Điện thờ chính",
      promptPreview: "Dược Lão vung tay phóng ra màn chắn năng lượng xanh ngọc bích bao bọc lấy cả hai...",
      visualBeatCount: 2,
    },
  ],
}

export const DEMO_VISUAL_BEATS: VisualBeat[] = [
  // Chapter 03 - Scene 1: Lối vào cổ mộ (3 beats)
  {
    id: "beat-3-1-1",
    sceneId: "scene-3-1",
    chapterId: "chap-03",
    beatNumber: 1,
    title: "Tiêu Viêm đứng trước cửa cổ mộ",
    prompt: "Thiếu niên Tiêu Viêm khoác áo choàng đen đứng trước cửa lăng mộ đá ngàn năm phủ đầy rêu phong, sương mù lạnh buốt bốc lên từ mặt đất, điện ảnh 4k, cinematic lighting",
    dialogue: "Lối vào này... dường như đã bị phong ấn hàng trăm năm rồi.",
    character: "Tiêu Viêm",
    characterAvatar: demoAvatars[0],
    location: "Cửa cổ mộ",
    duration: "00:03",
    cameraShot: "Trung cảnh",
    cameraMovement: "Dolly",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Đã tạo",
    thumb: demoProjects[0],
    lighting: "Ánh sáng mờ ảo trong sương",
  },
  {
    id: "beat-3-1-2",
    sceneId: "scene-3-1",
    chapterId: "chap-03",
    beatNumber: 2,
    title: "Phủi bụi ký tự cổ đại phát sáng",
    prompt: "Bàn tay thiếu niên phủi nhẹ lớp bụi dày trên phiến đá hoa cương, những ký tự cổ ngữ phát ra ánh sáng lam nhạt huyền bí, tàn tro bay lơ lửng trong không khí",
    dialogue: "Ký tự này... chính là nơi phong ấn Hồn Cốt Quyết!",
    character: "Tiêu Viêm",
    characterAvatar: demoAvatars[0],
    location: "Cửa cổ mộ",
    duration: "00:05",
    cameraShot: "Cận cảnh",
    cameraMovement: "Zoom in",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Đã tạo",
    thumb: demoProjects[1],
    lighting: "Lam quang tự phát sáng",
  },
  {
    id: "beat-3-1-3",
    sceneId: "scene-3-1",
    chapterId: "chap-03",
    beatNumber: 3,
    title: "Dược Lão vuốt râu cảnh báo",
    prompt: "Linh hồn Dược Lão bán trong suốt phiêu phù bên cạnh, ánh mắt ngưng trọng quan sát khí tức quanh cửa mộ, thần thái cao nhân bí ẩn",
    dialogue: "Cẩn thận, khí tức nơi này không hề đơn giản đâu đồ nhi.",
    character: "Dược Lão",
    characterAvatar: demoAvatars[1],
    location: "Cửa cổ mộ",
    duration: "00:04",
    cameraShot: "Trung cảnh",
    cameraMovement: "Tĩnh",
    generationStrategy: "IMAGE_TO_VIDEO",
    status: "Đã tạo",
    thumb: demoProjects[2],
    lighting: "Hào quang linh hồn trắng bạc",
  },

  // Chapter 03 - Scene 2: Khám phá điện thờ (4 beats)
  {
    id: "beat-3-2-1",
    sceneId: "scene-3-2",
    chapterId: "chap-03",
    beatNumber: 1,
    title: "Bước vào điện thờ cổ u ám",
    prompt: "Tiêu Viêm bước từng bước thận trọng vào đại điện ngầm, những cột đá chạm khắc long phượng sừng sững, không gian tĩnh lặng rợn người",
    dialogue: "Không một tiếng động... nhưng áp lực thật nghẹt thở.",
    character: "Tiêu Viêm",
    characterAvatar: demoAvatars[0],
    location: "Điện thờ chính",
    duration: "00:04",
    cameraShot: "Toàn cảnh",
    cameraMovement: "Pan trái",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Đã tạo",
    thumb: demoProjects[3],
    lighting: "Ánh đuốc le lói u tối",
  },
  {
    id: "beat-3-2-2",
    sceneId: "scene-3-2",
    chapterId: "chap-03",
    beatNumber: 2,
    title: "Quan sát bàn thờ đá trung tâm",
    prompt: "Bàn thờ đá nguyên khối đặt giữa điện thờ, bên trên có hộp ngọc phát ra vầng sáng tím mờ, xung quanh là trận pháp bát quái",
    dialogue: "Chiếc hộp ngọc kia chắc chắn chứa bảo vật.",
    character: "Tiêu Viêm",
    characterAvatar: demoAvatars[0],
    location: "Điện thờ chính",
    duration: "00:05",
    cameraShot: "Trung cảnh",
    cameraMovement: "Dolly",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Đã tạo",
    thumb: demoProjects[0],
    lighting: "Tím huyền ảo tương phản cao",
  },
  {
    id: "beat-3-2-3",
    sceneId: "scene-3-2",
    chapterId: "chap-03",
    beatNumber: 3,
    title: "Tiêu Viêm đưa tay mở hộp ngọc",
    prompt: "Góc máy cận cảnh bàn tay Tiêu Viêm chạm vào khóa hộp ngọc, năng lượng cổ xưa giải phóng từng đợt sóng gợn lăn tăn",
    dialogue: "Mở ra nào!",
    character: "Tiêu Viêm",
    characterAvatar: demoAvatars[0],
    location: "Điện thờ chính",
    duration: "00:06",
    cameraShot: "Cận cảnh",
    cameraMovement: "Zoom in",
    generationStrategy: "IMAGE_TO_VIDEO",
    status: "Đang tạo",
    thumb: demoProjects[1],
    lighting: "Sóng năng lượng phát quang",
  },
  {
    id: "beat-3-2-4",
    sceneId: "scene-3-2",
    chapterId: "chap-03",
    beatNumber: 4,
    title: "Bản văn Hồn Cốt Quyết xuất hiện",
    prompt: "Cuộn trục bằng xương ngọc lơ lửng giữa không trung, từng dòng chữ khắc kim sắc ánh lên lộng lẫy",
    dialogue: "Quả đúng là Hồn Cốt Quyết trong truyền thuyết!",
    character: "Dược Lão",
    characterAvatar: demoAvatars[1],
    location: "Điện thờ chính",
    duration: "00:04",
    cameraShot: "Đặc tả",
    cameraMovement: "Tĩnh",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Đang tạo",
    thumb: demoProjects[2],
    lighting: "Kim sắc chói lọi",
  },

  // Chapter 03 - Scene 3: Hộ mộ thú thức tỉnh (3 beats)
  {
    id: "beat-3-3-1",
    sceneId: "scene-3-3",
    chapterId: "chap-03",
    beatNumber: 1,
    title: "Mặt đất rung chuyển dữ dội",
    prompt: "Toàn bộ sàn đá điện thờ rạn nứt, đất đá rung bần bật, bụi tro từ trần hang đổ sụp xuống như mưa",
    dialogue: "Chuyện gì vậy? Động đất ư?",
    character: "Tiêu Viêm",
    characterAvatar: demoAvatars[0],
    location: "Vực sâu điện thờ",
    duration: "00:05",
    cameraShot: "Toàn cảnh",
    cameraMovement: "Tracking",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Chờ tạo",
    thumb: demoProjects[3],
    lighting: "Bụi mù u ám",
  },
  {
    id: "beat-3-3-2",
    sceneId: "scene-3-3",
    chapterId: "chap-03",
    beatNumber: 2,
    title: "Cột đá lớn sụp đổ chắn lối",
    prompt: "Cột trụ khổng lồ ngàn năm gãy đôi đổ ầm xuống mặt đất, khói bụi tung mù mịt cản trở lối rút lui",
    dialogue: "Lối ra bị chặn mất rồi!",
    character: "Tiêu Viêm",
    characterAvatar: demoAvatars[0],
    location: "Vực sâu điện thờ",
    duration: "00:04",
    cameraShot: "Trung cảnh",
    cameraMovement: "Pan phải",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Chờ tạo",
    thumb: demoProjects[0],
    lighting: "Bụi mù và tia lửa va đập",
  },
  {
    id: "beat-3-3-3",
    sceneId: "scene-3-3",
    chapterId: "chap-03",
    beatNumber: 3,
    title: "Hộ mộ thú trồi lên mắt đỏ rực",
    prompt: "Từ hố sâu nứt toác, bóng đen cự thú khổng lồ trồi lên, đôi mắt đỏ rực như hai vầng thái dương rực lửa, tiếng gầm vang dội làm rung chuyển không gian",
    dialogue: "Cẩn thận! Hộ mộ thú đã thức tỉnh!",
    character: "Dược Lão",
    characterAvatar: demoAvatars[1],
    location: "Vực sâu điện thờ",
    duration: "00:06",
    cameraShot: "Toàn cảnh",
    cameraMovement: "Zoom out",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Chờ tạo",
    thumb: demoProjects[1],
    lighting: "Hỏa quang đỏ rực tương phản tối",
  },

  // Chapter 03 - Scene 4: Màn chắn ngọc bích (2 beats)
  {
    id: "beat-3-4-1",
    sceneId: "scene-3-4",
    chapterId: "chap-03",
    beatNumber: 1,
    title: "Dược Lão vung tay kết ấn",
    prompt: "Dược Lão bay vọt lên không trung, đôi bàn tay kết thủ ấn liên hồi, linh hồn lực bùng nổ cuốn phăng lớp bụi mù xung quanh",
    dialogue: "Để lão phu cản nó lại!",
    character: "Dược Lão",
    characterAvatar: demoAvatars[1],
    location: "Điện thờ chính",
    duration: "00:04",
    cameraShot: "Cận cảnh",
    cameraMovement: "Dolly",
    generationStrategy: "IMAGE_TO_VIDEO",
    status: "Đã tạo",
    thumb: demoProjects[2],
    lighting: "Thanh quang ngọc bích rực rỡ",
  },
  {
    id: "beat-3-4-2",
    sceneId: "scene-3-4",
    chapterId: "chap-03",
    beatNumber: 2,
    title: "Màn chắn năng lượng bao bọc cả hai",
    prompt: "Màn chắn bán cầu năng lượng màu xanh ngọc bích bao bọc Tiêu Viêm và Dược Lão, chống đỡ đòn đánh sấm sét của cự thú, tia lửa năng lượng nổ tung rực sáng",
    dialogue: "Chạy về phía đường ngầm bên phải!",
    character: "Dược Lão",
    characterAvatar: demoAvatars[1],
    location: "Điện thờ chính",
    duration: "00:05",
    cameraShot: "Trung cảnh",
    cameraMovement: "Tĩnh",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Đã tạo",
    thumb: demoProjects[3],
    lighting: "Ngọc bích phản xạ ánh lửa",
  },

  // Chapter 01 Beats (8 beats across 3 scenes)
  {
    id: "beat-1-1-1",
    sceneId: "scene-1-1",
    chapterId: "chap-01",
    beatNumber: 1,
    title: "Tiêu Viêm nhìn cổng gia tộc",
    prompt: "Thiếu niên đứng trước cổng lớn Tiêu Gia dưới nắng chiều vàng óng, bóng lưng quyết tâm",
    dialogue: "Ba năm hẹn ước, Tiêu Viêm này nhất định sẽ đến Vân Lam Tông!",
    character: "Tiêu Viêm",
    characterAvatar: demoAvatars[0],
    location: "Cổng thành Tiêu Gia",
    duration: "00:03",
    cameraShot: "Trung cảnh",
    cameraMovement: "Dolly",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Đã tạo",
    thumb: demoProjects[0],
  },
  {
    id: "beat-1-1-2",
    sceneId: "scene-1-1",
    chapterId: "chap-01",
    beatNumber: 2,
    title: "Tiêu Huân Nhi vẫy tay từ xa",
    prompt: "Thiếu nữ áo tím thanh nhã đứng trên lầu cao, ánh mắt dõi theo đầy lưu luyến",
    dialogue: "Tiêu Viêm ca ca, muội sẽ chờ huynh trở về.",
    character: "Huân Nhi",
    characterAvatar: demoAvatars[2],
    location: "Cổng thành Tiêu Gia",
    duration: "00:04",
    cameraShot: "Cận cảnh",
    cameraMovement: "Zoom in",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Đã tạo",
    thumb: demoProjects[1],
  },
  {
    id: "beat-1-1-3",
    sceneId: "scene-1-1",
    chapterId: "chap-01",
    beatNumber: 3,
    title: "Tiêu Viêm quay lưng dứt khoát",
    prompt: "Bước chân dứt khoát bước ra khỏi bóng cổng thành, hướng về chân trời xa xôi",
    dialogue: "Đi thôi!",
    character: "Tiêu Viêm",
    characterAvatar: demoAvatars[0],
    location: "Cổng thành Tiêu Gia",
    duration: "00:03",
    cameraShot: "Toàn cảnh",
    cameraMovement: "Tracking",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Đã tạo",
    thumb: demoProjects[2],
  },
  {
    id: "beat-1-2-1",
    sceneId: "scene-1-2",
    chapterId: "chap-01",
    beatNumber: 1,
    title: "Tiêu Viêm đi vào rừng Ma Thú",
    prompt: "Con đường mòn gập ghềnh rợp bóng cổ thụ, tiếng chim hót hoang sơ",
    dialogue: "Nơi này quả nhiên nguy hiểm trùng trùng.",
    character: "Tiêu Viêm",
    characterAvatar: demoAvatars[0],
    location: "Chân dãy núi Ma Thú",
    duration: "00:04",
    cameraShot: "Toàn cảnh",
    cameraMovement: "Pan trái",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Đã tạo",
    thumb: demoProjects[3],
  },
  {
    id: "beat-1-2-2",
    sceneId: "scene-1-2",
    chapterId: "chap-01",
    beatNumber: 2,
    title: "Bóng ma thú lướt qua",
    prompt: "Ánh mắt đỏ quạch thoáng ẩn hiện sau bụi rậm um tùm",
    dialogue: "Có động tĩnh!",
    character: "Tiêu Viêm",
    characterAvatar: demoAvatars[0],
    location: "Chân dãy núi Ma Thú",
    duration: "00:03",
    cameraShot: "Cận cảnh",
    cameraMovement: "Pan phải",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Đã tạo",
    thumb: demoProjects[0],
  },
  {
    id: "beat-1-2-3",
    sceneId: "scene-1-2",
    chapterId: "chap-01",
    beatNumber: 3,
    title: "Tìm thấy hang đá trú ẩn",
    prompt: "Hang đá nhỏ khuất sau rèm dây leo, Tiêu Viêm nhanh chóng ẩn nấp",
    dialogue: "Tối nay tạm thời ở đây.",
    character: "Tiêu Viêm",
    characterAvatar: demoAvatars[0],
    location: "Chân dãy núi Ma Thú",
    duration: "00:04",
    cameraShot: "Trung cảnh",
    cameraMovement: "Dolly",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Đã tạo",
    thumb: demoProjects[1],
  },
  {
    id: "beat-1-3-1",
    sceneId: "scene-1-3",
    chapterId: "chap-01",
    beatNumber: 1,
    title: "Chiếc nhẫn đen phát sáng",
    prompt: "Chiếc nhẫn sắt đen sì trên ngón tay bỗng rung lên nhè nhẹ, tỏa khói trắng",
    dialogue: "Nó... lại hút đấu khí của mình sao?",
    character: "Tiêu Viêm",
    characterAvatar: demoAvatars[0],
    location: "Hang đá tạm trú",
    duration: "00:04",
    cameraShot: "Đặc tả",
    cameraMovement: "Zoom in",
    generationStrategy: "IMAGE_TO_VIDEO",
    status: "Đã tạo",
    thumb: demoProjects[2],
  },
  {
    id: "beat-1-3-2",
    sceneId: "scene-1-3",
    chapterId: "chap-01",
    beatNumber: 2,
    title: "Dược Lão hiện thân",
    prompt: "Lão giả râu tóc bạc phơ hiện ra từ làn sương trắng, nụ cười đắc ý",
    dialogue: "Tiểu tử, ba năm nay đa tạ đấu khí của ngươi!",
    character: "Dược Lão",
    characterAvatar: demoAvatars[1],
    location: "Hang đá tạm trú",
    duration: "00:05",
    cameraShot: "Trung cảnh",
    cameraMovement: "Tĩnh",
    generationStrategy: "TEXT_TO_VIDEO",
    status: "Đã tạo",
    thumb: demoProjects[3],
  },
]

export function getVisualBeatsForChapter(chapterId: string): VisualBeat[] {
  return DEMO_VISUAL_BEATS.filter((b) => b.chapterId === chapterId)
}

export function getVisualBeatsForScene(sceneId: string): VisualBeat[] {
  return DEMO_VISUAL_BEATS.filter((b) => b.sceneId === sceneId)
}

export const DEFAULT_ANALYSIS_SETTINGS: AnalysisSettings = {
  videoStyle: "donghua",
  pacing: "medium",
  targetSceneCount: 4,
  visualBeatDetailLevel: "high",
  autoDetectCharacters: true,
  autoExtractLocations: true,
}

export const DEMO_ANALYSIS_RESULT: AnalysisResult = {
  characterCount: 2,
  locationCount: 2,
  sceneCount: 4,
  visualBeatCount: 12,
  characters: [
    { id: "c1", name: "Tiêu Viêm", role: "Nhân vật chính" },
    { id: "c2", name: "Dược Lão", role: "Sư phụ / Hỗ trợ" },
  ],
  locations: [
    { id: "l1", name: "Cửa cổ mộ", description: "Rừng u ám" },
    { id: "l2", name: "Điện thờ chính", description: "Cổ mộ ngàn năm" },
  ],
  completedAt: "14:32",
}

export const DEMO_ANALYSIS_STEPS: AnalysisProgressStep[] = [
  { id: "s1", label: "Phân tích cú pháp cốt truyện", duration: "0.8s", status: "completed" },
  { id: "s2", label: "Trích xuất nhân vật & thực thể", duration: "1.2s", status: "completed" },
  { id: "s3", label: "Phân đoạn cảnh theo mạch truyện", duration: "2.1s", status: "completed" },
  { id: "s4", label: "Tạo visual beats chi tiết", duration: "3.4s", status: "completed" },
]
